[package]
name = "cube-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description.workspace = true

[[bin]]
name = "cube-cli"
path = "src/main.rs"

[dependencies]
cube-core = { path = "../cube-core" }
clap = { version = "4.5", features = ["derive"] }


